Traceback (most recent call last):
  File "c:\Users\jonma\Documents\GitHub\Python-Exercises\Useful_modules\traceback_module.py", line 39, in faulty
    1 / 0
ZeroDivisionError: division by zero
